### ISSUE TITLE
5. Transaction , merkle tree and block

### ISSUE THREAD

**Issue by jjj-netizen** [lecture4u/web-klein-schwarze-box#26] opened 2019-05-23 06:38 UTC
# Transaction&Block 
![image](https://user-images.githubusercontent.com/32332719/58231040-ebf4aa00-7d70-11e9-9d32-df2a12c69b2c.png)

## 1) Transactions
* push  Add Transaction button, create transaction(i) and input data.
## 2) Merkle Tree
* Then push make MerkleTree button, create a merkle tree about transactions.
## 3) Block hash
* can get nonce, get previous hash and add to block about transactions.

**Comment by yoseplee** [comment] 2019-05-26 08:58
# addTransaction() has merged to Vue, not Api due to its role in REST based architecture.
details are below code
```java
private void addTransaction(AnchorPane tranPane, String paneName){
		
		if(paneName.equals("transaction")){
			TransactionNode tn = new TransactionNode("Transaction"+transactionNumber,transactionXpoint,transactionYpoint);
			tn.addToPane(tranPane);
			transactionFieldList.add(tn.getNode());
			
			if(transactionXpoint>200){
				transactionYpoint +=61;
				transactionXpoint =14;
			}
			else{
			    transactionXpoint +=200;
			    
			}
			transactionNumber++;
			tn.getNode().requestFocus();
		}
		else if(paneName.equals("wallet1")){
			TransactionNode tn = new TransactionNode("Transaction"+walletNumber,wallet1Xpoint,wallet1Ypoint);
			tn.addToPane(tranPane);
			//wallet1FieldList.add(tn.getNode());
			allWalletFieldList.add(tn.getNode());
			allWalletFieldWallet.add("wallet1");
			if(wallet1Xpoint>400){
				wallet1Ypoint +=61;
				wallet1Xpoint =14;
			}
			else{
				wallet1Xpoint +=200;
			    
			}
			walletNumber++;
			tn.getNode().requestFocus();
		}
		else if(paneName.equals("wallet2")){
			TransactionNode tn = new TransactionNode("Transaction"+walletNumber,wallet2Xpoint,wallet2Ypoint);
			tn.addToPane(tranPane);
			//wallet2FieldList.add(tn.getNode());
			allWalletFieldList.add(tn.getNode());
			allWalletFieldWallet.add("wallet2");
			if(wallet2Xpoint>400){
				wallet2Ypoint +=61;
				wallet2Xpoint =14;
			}
			else{
				wallet2Xpoint +=200;
			    
			}
			walletNumber++;
			tn.getNode().requestFocus();
		}
		else if(paneName.equals("wallet3")){
			TransactionNode tn = new TransactionNode("Transaction"+walletNumber,wallet3Xpoint,wallet3Ypoint);
			tn.addToPane(tranPane);
			//wallet3FieldList.add(tn.getNode());
			allWalletFieldList.add(tn.getNode());
			allWalletFieldWallet.add("wallet3");
			if(wallet3Xpoint>400){
				wallet3Ypoint +=61;
				wallet3Xpoint =14;
			}
			else{
				wallet3Xpoint +=200;
			    
			}
			walletNumber++;
			tn.getNode().requestFocus();
		}	
    }
```
as legacy program, addTransaction() is responsible to remember transaction log and be ready to generate merkle tree. but in this context, such responsibility is no more upon to server, but client.
therefore this part is implemented on front page using vue.js

**Comment by yoseplee** [comment] 2019-05-26 10:51
So far, button operation is so ambiguous that I cannot grasp what's going on between classes
1. GetNonce -> ambiguous
2. Get Previous Hash -> ambiguous. possibly random due to legacy code at initializer
3. add to block -> ambiguous. but it clearly means the merkle root

**Comment by yoseplee** [comment] 2019-05-27 04:46
Today(27, May) I've confirmed ambiguous point above with professor.
As this transaction part is nothing to do with actual blockchain, those parameters cannot be regarded as specific value, so at this point, we use random.

**Comment by yoseplee** [comment] 2019-05-29 13:21
successfully instantiate a tinyBlock class on test tool. see attributes below.

![image](https://user-images.githubusercontent.com/29854277/58560300-cfb8a780-825f-11e9-9a34-7a39abbe9836.png)

related to commit: 3ae9a62453ebbe78e860490dd1c949004331fc9b

this extraction will be utilized to ApiController as soon as possible

**Comment by yoseplee** [comment] 2019-05-29 14:01
need to know why this code is needed
``` java 
int merkleCount = 2;
        while(merkleCount < transactionList.size()) {
            merkleCount *= 2;
        }
```

you can find this code in core>javaFXML>SampleController.java 272~274

**Comment by yoseplee** [comment] 2019-05-30 16:12
I've encountered an vue related error at the final stage of this part :(

<img width="1040" alt="Screen Shot 2019-05-31 at 01 07 31" src="https://user-images.githubusercontent.com/29854277/58646515-83916400-8340-11e9-9154-fa22303a5fda.png">

I do remember that I've solved the same problem but I don't get it right now. I need some sleep
343cabda2b1f4058bf328c562896081038928697

**Comment by yoseplee** [comment] 2019-05-31 11:32
error solved! and all the features without visualization are all implemented

**Comment by yoseplee** [comment] 2019-05-31 11:35
I close this issue due to related branch has merged into master branch

**Closed as completed by yoseplee** 2019-05-31 11:35 UTC
Labels: requirement
